config/routes.rb
Rails.application.routes.draw do
  get 'checkout/show'
  get 'checkout/create'
  get 'carts/show'
  get 'home/index'
  devise_for :admins
  devise_for :users

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    resources :products
    resources :orders, only: [:index, :show]

    resources :reviews, only: [:index, :destroy] do
      member do
        post :hide
      end
    end
  end

  namespace :users do
    get 'dashboard', to: 'dashboard#index'
  end

  resources :cart_items, only: [:create, :destroy, :show]
  resources :orders, only: [:new, :create, :show]
  resource :cart, only: [:show]
  get 'checkout', to: 'checkouts#show'
  post 'checkout', to: 'checkouts#create'

  resources :products, only: [:index, :show, :home] do
    resources :reviews, only: [:new, :create, :index, :edit, :update, :destroy]
  end

  resource :wallet, only: [:show, :update]

  root 'home#index'
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items, dependent: :destroy

  validates :total_price, numericality: { greater_than: 0 }

  enum shipment_status: { shipment_pending: 'shipment_pending', shipped: 'shipped', delivered: 'delivered' }
  enum payment_status: { payment_pending: 'payment_pending', paid: 'paid', refunded: 'refunded' }

  def calculate_total_price
    self.total_price = order_items.sum(&:total_price)
  end
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
      # Ensure only admins can access this controller
      before_action :authenticate_admin!
  
      def index
        @orders = Order.all # Fetch all orders for the admin view
      end
  
      def show
        @order = Order.includes(:user).find(params[:id])
      end
end
  

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_user!

  def new
    @order = Order.new
  end

  def create
    @order = current_user.orders.new(order_params)
    @order.shipment_status = 'pending'
    @order.payment_status = 'unpaid'

    if @order.save
      current_user.cart_items.each do |cart_item|
        @order.order_items.create!(
          product_variant_id: cart_item.product_variant_id,
          quantity: cart_item.quantity,
          price: cart_item.price
        )
      end

      current_user.cart_items.destroy_all

      redirect_to order_path(@order), notice: 'Order placed successfully!'
    else
      render :new
    end
  end
  
  def show 
    @order = current_user.orders.find(params[:id])
  end 
  private

  def order_params
    params.require(:order).permit(:total_price)
  end
end

app/views/admin/orders/index.html.slim
h1 Orders

ul
  - @orders.each do |order|
    li
      = link_to "Order ##{order.id}", admin_order_path(order)


= link_to 'Back to Admin Dashboard', admin_dashboard_path, class: 'btn btn-primary'

app/views/admin/orders/show.html.slim
p
  | Order ID: 
  = @order.id

p
  | Customer: 
  = @order.user.full_name

p
  | Total Amount: 
  = number_to_currency(@order.total_price)

p
  | Status: 
  = @order.shipment_status

p
  | Payment: 
  = @order.payment_status
h3 Ordered Items:

ul
  - @order.order_items.each do |item|
    li
      | Item: 
      = item.product_variant.product.name
    li      
      | Quantity: 
      = item.quantity
    li
      | Price: 
      = number_to_currency(item.price)

= link_to 'Admin Dashboard', admin_dashboard_path, class: 'btn btn-primary'

p
    = link_to 'Back to Orders',  admin_orders_path, class: 'btn btn-primary'