config/routes.rb
Rails.application.routes.draw do
  get 'checkout/show'
  get 'checkout/create'
  get 'carts/show'
  get 'home/index'
  devise_for :admins
  devise_for :users

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    resources :products
    resources :orders, only: [:index, :show]

    resources :reviews, only: [:index, :destroy] do
      member do
        post :hide
      end
    end
  end

  namespace :users do
    get 'dashboard', to: 'dashboard#index'
  end

  resources :cart_items, only: [:create, :destroy, :show]
  resources :orders, only: [:new, :create, :show]
  resource :cart, only: [:show]
  get 'checkout', to: 'checkouts#show'
  post 'checkout', to: 'checkouts#create'

  resources :products, only: [:index, :show, :home] do
    resources :reviews, only: [:new, :create, :index, :edit, :update, :destroy]
  end

  resource :wallet, only: [:show, :update]

  root 'home#index'
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart_items = current_user.cart_items.includes(:product_variant)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/show.html.slim
h1 Your Cart

h5 Your Wallet Balance
p = number_to_currency(current_user.wallet)

- if @cart_items.any?
  table.table
    thead
      tr
        th Product Name
        th Product Variant
        th Quantity
        th Price
        th Total Price
    tbody
      - @cart_items.each do |cart_item|
        tr
          td = cart_item.product_variant.product.name
          td = cart_item.product_variant.name
          td = cart_item.quantity
          td = number_to_currency(cart_item.price)
          td = number_to_currency(cart_item.total_price)
  p
    = link_to 'Checkout', checkout_path, class: 'btn btn-primary'
- else
  p Your cart is empty.


p
  = link_to 'User Dashboard', users_dashboard_path, class: 'btn btn-primary'
p 
  = link_to 'Back To Products', products_path