config/routes.rb
Rails.application.routes.draw do
  get 'checkout/show'
  get 'checkout/create'
  get 'carts/show'
  get 'home/index'
  devise_for :admins
  devise_for :users

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    resources :products
    resources :orders, only: [:index, :show]

    resources :reviews, only: [:index, :destroy] do
      member do
        post :hide
      end
    end
  end

  namespace :users do
    get 'dashboard', to: 'dashboard#index'
  end

  resources :cart_items, only: [:create, :destroy, :show]
  resources :orders, only: [:new, :create, :show]
  resource :cart, only: [:show]
  get 'checkout', to: 'checkouts#show'
  post 'checkout', to: 'checkouts#create'

  resources :products, only: [:index, :show, :home] do
    resources :reviews, only: [:new, :create, :index, :edit, :update, :destroy]
  end

  resource :wallet, only: [:show, :update]

  root 'home#index'
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :product_variants, dependent: :destroy
    has_many :reviews
    accepts_nested_attributes_for :product_variants, allow_destroy: true
    validates :name, presence: true, length: {minimum: 5, maximum: 50}
    validates :description, presence: true, length: {minimum: 10, maximum: 100}
  end
  

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: %i[show edit update destroy]

  # GET /admin/products
  def index
    @products = Product.all
  end

  # GET /admin/products/1
  def show
  end

  # GET /admin/products/new
  def new
    @product = Product.new
    @product.product_variants.build # Initialize a variant for the form
  end

  # POST /admin/products
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product), notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # GET /admin/products/1/edit
  def edit
    @product.product_variants.build if @product.product_variants.empty? # Ensure at least one variant exists for editing
  end

  # PATCH/PUT /admin/products/1
  def update
    if @product.update(product_params)
      redirect_to admin_product_path(@product), notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/products/1
  def destroy
    @product.destroy
    redirect_to admin_products_url, notice: 'Product was successfully destroyed.'
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, product_variants_attributes: [:id, :name, :price, :stock_quantity, :_destroy])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: %i[index show]
  before_action :set_product, only: %i[show]
  
  helper_method :sort_column, :sort_direction

  # GET /products
  def index
    @products = Product.all.order("#{sort_column} #{sort_direction}")
  end

  # GET /products/1
  def show
    @reviews = @product.reviews.includes(:user) # Loads the reviews for the product
    @can_review = can_review? 
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # POST /products
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # GET /products/1/edit
  def edit
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, product_variants_attributes: [:id, :name, :price, :stock_quantity, :_destroy])
  end

  def authorize_admin
    redirect_to products_path, alert: 'You are not authorized to perform this action.' unless current_admin
  end

  def sort_column
    %w[name description].include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def can_review?
    OrderItem.joins(:order)
              .where(orders: { user_id: current_user.id }, product_variant_id: @product.product_variants.pluck(:id))
              .exists?
  end
  
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.slim
= form_with model: [:admin, @product], data:{turbo: false} do |f|
  - if @product.errors.any?
    #error_explanation
      h2 = "#{pluralize(@product.errors.count, 'error')} prohibited this product from being saved:"
      ul
        - @product.errors.full_messages.each do |message|
          li = message

  div
    = f.label :name
    = f.text_field :name

  div
    = f.label :description
    = f.text_area :description

  div 
     h3 Product Variants


  div data-controller="fields" data-fields-target="container"
    template data-fields-target="template"
      = f.fields_for :product_variants, ProductVariant.new, child_index: 'NEW_RECORD' do |pv_form|
        = render 'product_variant_fields', f: pv_form

    = f.fields_for :product_variants do |pv_form|
      = render 'product_variant_fields', f: pv_form    
    .add-variant data-fields-target="addButton"
      = link_to 'Add Variant', '#', class: 'btn btn-secondary', data: { action: "click->fields#add" }

  div
    = f.submit 'Save Product', class: 'btn btn-primary'

app/views/admin/products/_product.html.slim
.tr
  td = product.name
  td = product.description
  td = product.variants
  td
    = link_to "Show", admin_product_path(product)
    | |
    = link_to "Edit", edit_admin_product_path(product)
    | |
    = button_to "Destroy", admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' }

app/views/admin/products/_product_variant_fields.html.slim
.fields
  .nested-fields
    = f.hidden_field :_destroy
    div
      = f.label :name
      = f.text_field :name

    div
      = f.label :price
      = f.number_field :price

    div
      = f.label :stock_quantity
      = f.number_field :stock_quantity

    div
      = link_to 'Remove', '#', class: 'btn btn-danger remove_fields', data: { action: "click->fields#remove" }

app/views/admin/products/edit.html.slim
h1 Edit Product

= render 'form'

app/views/admin/products/index.html.slim
h1 Products

table
  thead
    tr
      th Name
      th Description
      th Variants
      th Actions
  tbody
    - @products.each do |product|
      tr
        td = product.name
        td = product.description
        td
          ul
            - product.product_variants.each do |variant|
              li = "#{variant.name} - $#{variant.price} (Stock: #{variant.stock_quantity})"
        td
          = link_to 'Show ', admin_product_path(product), class: 'btn btn-info'
          = link_to 'Edit ', edit_admin_product_path(product), class: 'btn btn-warning'
          = button_to 'Destroy', admin_product_path(product), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'

= link_to 'New Product', new_admin_product_path, class: 'btn btn-primary'
p
  = link_to 'Admin Dashboard', admin_dashboard_path, class: 'btn btn-primary'

app/views/admin/products/new.html.slim
p style="color: green" = notice


h1 New Product

= render 'form'

app/views/admin/products/show.html.slim
h1 = @product.name

div
  p
    strong Description: 
    = @product.description

hr

h2 Product Variants

- if @product.product_variants.any?
  ul
    - @product.product_variants.each do |variant|
      li
        p
          strong Name: 
          = variant.name
        p
          strong Price: 
          = number_to_currency(variant.price)
        p
          strong Stock Quantity: 
          = variant.stock_quantity
else
  p No other variants available.

hr

= link_to "Edit this product", edit_admin_product_path(@product), class: 'btn btn-primary'
= button_to "Destroy this product", admin_product_path(@product), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger'
= link_to "Back to Products", admin_products_path, class: 'btn btn-secondary'