config/routes.rb
Rails.application.routes.draw do
  get 'checkout/show'
  get 'checkout/create'
  get 'carts/show'
  get 'home/index'
  devise_for :admins
  devise_for :users

  namespace :admin do
    get 'dashboard', to: 'dashboard#index'
    resources :products
    resources :orders, only: [:index, :show]

    resources :reviews, only: [:index, :destroy] do
      member do
        post :hide
      end
    end
  end

  namespace :users do
    get 'dashboard', to: 'dashboard#index'
  end

  resources :cart_items, only: [:create, :destroy, :show]
  resources :orders, only: [:new, :create, :show]
  resource :cart, only: [:show]
  get 'checkout', to: 'checkouts#show'
  post 'checkout', to: 'checkouts#create'

  resources :products, only: [:index, :show, :home] do
    resources :reviews, only: [:new, :create, :index, :edit, :update, :destroy]
  end

  resource :wallet, only: [:show, :update]

  root 'home#index'
end

app/models/product.rb
class Product < ApplicationRecord
    has_many :product_variants, dependent: :destroy
    has_many :reviews
    accepts_nested_attributes_for :product_variants, allow_destroy: true
    validates :name, presence: true, length: {minimum: 5, maximum: 50}
    validates :description, presence: true, length: {minimum: 10, maximum: 100}
  end
  

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :authenticate_admin!
  before_action :set_product, only: %i[show edit update destroy]

  # GET /admin/products
  def index
    @products = Product.all
  end

  # GET /admin/products/1
  def show
  end

  # GET /admin/products/new
  def new
    @product = Product.new
    @product.product_variants.build # Initialize a variant for the form
  end

  # POST /admin/products
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to admin_product_path(@product), notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # GET /admin/products/1/edit
  def edit
    @product.product_variants.build if @product.product_variants.empty? # Ensure at least one variant exists for editing
  end

  # PATCH/PUT /admin/products/1
  def update
    if @product.update(product_params)
      redirect_to admin_product_path(@product), notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /admin/products/1
  def destroy
    @product.destroy
    redirect_to admin_products_url, notice: 'Product was successfully destroyed.'
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_params
      params.require(:product).permit(:name, :description, product_variants_attributes: [:id, :name, :price, :stock_quantity, :_destroy])
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!, only: %i[index show]
  before_action :set_product, only: %i[show]
  
  helper_method :sort_column, :sort_direction

  # GET /products
  def index
    @products = Product.all.order("#{sort_column} #{sort_direction}")
  end

  # GET /products/1
  def show
    @reviews = @product.reviews.includes(:user) # Loads the reviews for the product
    @can_review = can_review? 
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # POST /products
  def create
    @product = Product.new(product_params)
    if @product.save
      redirect_to @product, notice: 'Product was successfully created.'
    else
      render :new
    end
  end

  # GET /products/1/edit
  def edit
  end

  # PATCH/PUT /products/1
  def update
    if @product.update(product_params)
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /products/1
  def destroy
    @product.destroy
    redirect_to products_url, notice: 'Product was successfully destroyed.'
  end

  private

  def set_product
    @product = Product.find(params[:id])
  end

  def product_params
    params.require(:product).permit(:name, :description, product_variants_attributes: [:id, :name, :price, :stock_quantity, :_destroy])
  end

  def authorize_admin
    redirect_to products_path, alert: 'You are not authorized to perform this action.' unless current_admin
  end

  def sort_column
    %w[name description].include?(params[:sort]) ? params[:sort] : "name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def can_review?
    OrderItem.joins(:order)
              .where(orders: { user_id: current_user.id }, product_variant_id: @product.product_variants.pluck(:id))
              .exists?
  end
  
end

app/helpers/admin/products_helper.rb
module Admin::ProductsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.slim
h1 = @product.name

div
  p
    strong Description: 
    = @product.description

hr

h2 Product Variants

- if @product.product_variants.any?
  ul
    - @product.product_variants.each do |variant|
      li
        p
          strong Name: 
          = variant.name
        p
          strong Price: 
          = number_to_currency(variant.price)
        p
          strong Stock Quantity: 
          = variant.stock_quantity
else
  p No other variants available.

hr

app/views/products/home.html.slim
h1 Home

div
  =< link_to "See our current Products", products_path

app/views/products/index.html.slim
h1 Products

table
  thead
    tr
      th
        = link_to 'Name', products_path(sort: 'name', direction: sort_direction == 'asc' ? 'desc' : 'asc'), data: { turbo_action: 'advance' }
      th
        = link_to 'Description', products_path(sort: 'description', direction: sort_direction == 'asc' ? 'desc' : 'asc'), data: { turbo_action: 'advance' }
      th Variants
      th Actions
  tbody
    - @products.each do |product|
      tr
        td = product.name
        td = product.description
        td
          - if product.product_variants.any?(&:in_stock?)
            = form_with url: cart_items_path, method: :post, class: 'form-inline', data: { turbo_frame: "product_#{product.id}" } do
              = hidden_field_tag :product_id, product.id
              = select_tag :product_variant_id, options_from_collection_for_select(product.product_variants, :id, :name_and_price), prompt: 'Select a variant', class: 'form-control'
              = number_field_tag :quantity, 1, in: 1..product.product_variants.maximum(:stock_quantity).to_i, class: 'form-control'
              = submit_tag 'Add to Cart', class: 'btn btn-success'
          - else
            span Out of Stock
        td
          = link_to 'Show', product_path(product), class: 'btn btn-info'
          = link_to 'Show Reviews', product_reviews_path(product), class: 'btn btn-secondary'
p
  = link_to 'User Dashboard', users_dashboard_path, class: 'btn btn-primary'

app/views/products/show.html.slim
p style="color: green" = notice

h2 = @product.name
p = @product.description

h3 Variants
ul
  - @product.product_variants.each do |variant|
    li
      | #{variant.name} - $#{variant.price} (Stock: #{variant.stock_quantity})
      - if variant.stock_quantity > 0
        = form_with url: cart_items_path, method: :post, class: 'form-inline' do
          = hidden_field_tag :product_variant_id, variant.id
          = number_field_tag :quantity, 1, in: 1..variant.stock_quantity, class: 'form-control'
          = submit_tag 'Add to Cart', class: 'btn btn-success'
      - else
        p.text-danger Out of Stock

= link_to "Back to Products", products_path, class: 'btn btn-secondary'

h3 Reviews

- @product.reviews.each do |review|
  div.review
    p
      strong = review.user.first_name
      | (Rating: #{review.rating} stars)
    p = review.comment

- if @can_review
  h4 Leave a Review
  = form_with model: [ @product, Review.new ], local: true do |form|
    .form-group
      = form.label :rating, "Rating (0-5)"
      = form.number_field :rating, in: 0..5, class: 'form-control'
      
    .form-group
      = form.label :comment, "Comment"
      = form.text_area :comment, class: 'form-control'
      
    = form.submit 'Submit Review', class: 'btn btn-primary'